var AhunterAPI=null,AhunterConfig=null,AhunterUtils=null;$(document).ready(function(){AhunterMainInit()});function AhunterMainInit(){1024>=$("body").width()&&($("body table").attr("width","100%"),$("body table").css("width","100%"));AhunterAPI=CreateAhunterAPI();AhunterConfig=CreateAhunterConfig();AhunterUtils=CreateAhunterUtils();$(".js-AhunterVersion").text(AhunterVersion)}
function CreateAhunterAPI(){var c={DataType:{TEXT:{id:0,title:"Текст"},ADDRESS:{id:1,title:"Адрес"},PHONE:{id:2,title:"Телефон"},PERSON:{id:3,title:"ФИО"},COMPANY:{id:4,title:"Компания"}},RegistryStatus:{INVALID:{id:0,title:"обработан с ошибкой"},UNPROCESSED:{id:1,title:"не обработан"},IN_QUEUE:{id:2,title:"в очереди на обработку"},IN_PROCESS:{id:3,title:"обрабатывается"},PROCESSED:{id:4,title:"обработан"},DELETED:{id:5,title:"удален"}},ReportItemType:{Field:{id:0,title:"Колонка реестра"},Section:{id:1,
title:"Секция реестра"},Selector:{id:2,title:"? езультат обработки"}},ResultPreset:{Any:{id:0,title:"Без ограничений",comment:"Любой результат будет попадать в выдачу"},Uniq:{id:1,title:"Однозначные",comment:"? езультат попадет в выдачу, если данные распознаны однозначно"},Multi:{id:2,title:"Многозначные",comment:"? езультат попадет в выдачу, если данные распознаны многозначно"},Unsure:{id:3,title:"Сомнительные",comment:"? езультат попадет в выдачу, если данные распознаны сомнительно"},Stable:{id:4,title:"Уверенные",
comment:"? езультат попадет в выдачу, если данные распознаны однозначно и уверенно"},Null:{id:5,title:"Отбракованные",comment:"? езультат попадет в выдачу, если данные не удалось распознать"},Custom:{id:6,title:"Свой фильтр",comment:"? езультат попадет в выдачу, если он отвчает условиям вашего фильтра"}},CSVItem:{GlobalBase:{id:0,title:"? езервируем начальное значение",comment:""},AltsAmount:{id:1,title:"Количество вариантов распознавания",comment:""},ProcessTime:{id:2,title:"Время обработки",comment:""},
ResultFlags:{id:3,title:"Флаги о результате обработки",comment:""},Address_Base:{id:100,title:"Отсюда начинаются поля адреса общего назначения",comment:""},AddressZip:{id:101,title:"Почтовый индекс адреса",comment:""},AOName_Base:{id:200,title:"Отсюда начинаются поля, соответствующие названиям АО на соответствующих уровнях адреса"},AOName_Region:{id:201,title:"Имя региона",comment:""},AOName_District:{id:202,title:"Имя района",comment:""},AOName_City:{id:203,title:"Имя города",comment:""},AOName_Place:{id:204,
title:"Имя населенного пункта",comment:""},AOName_Street:{id:205,title:"Имя улицы",comment:""},AOName_House:{id:206,title:"Номер дома",comment:""},AOName_Building:{id:207,title:"Номер корпуса",comment:""},AOName_Structure:{id:208,title:"Номер строения",comment:""},AOName_Flat:{id:209,title:"Номер квартиры",comment:""},AOName_Site:{id:210,title:"Имя территории",comment:""},AOType_Base:{id:300,title:"Отсюда начинаются поля, соответствующие типам АО на соответствующих уровнях адреса",comment:""},AOType_Region:{id:301,
title:"Тип региона",comment:""},AOType_District:{id:302,title:"Тип района",comment:""},AOType_City:{id:303,title:"Тип города",comment:""},AOType_Place:{id:304,title:"Тип населенного пункта",comment:""},AOType_Street:{id:305,title:"Тип улицы",comment:""},AOType_House:{id:306,title:"Тип номера дома",comment:""},AOType_Building:{id:307,title:"Тип корпуса",comment:""},AOType_Structure:{id:308,title:"Тип строения",comment:""},AOType_Flat:{id:309,title:"Тип квартиры",comment:""},AOType_Site:{id:310,title:"Тип территории",
comment:""},AddressCover_Base:{id:400,title:"Отсюда начинаются поля, содержащие информацию о текстовом покрытии адреса",comment:""},UnusedText:{id:401,title:"Неиспользованный текст",comment:""},AddressGEO_Base:{id:500,title:"Отсюда начинаются поля с результатом геокодирования адреса",comment:""},GEOLat:{id:501,title:"Географическая широта",comment:""},GEOLon:{id:502,title:"Географическая долгота",comment:""},GEOLevel:{id:503,title:"Уровень координат объекта",comment:""},AddressCodes_Base:{id:600,
title:"Отсюда начинаются поля с кодами адреса по справочникам",comment:""},AddressActualKLADR:{id:601,title:"Актуальный код КЛАД? ",comment:""},AddressActualFIAS:{id:602,title:"Актуальный код ФИАС",comment:""},AddressFIASGuid:{id:603,title:"Идентификатор адреса по ФИАС",comment:""},AddressFIASLevel:{id:604,title:"Уровень объекта, для которого получен идентификатор ФИАС",comment:""},AddressOKATO:{id:605,title:"Код адреса по ОКАТО",comment:""},AddressOKTMO:{id:606,title:"Код адреса по ОКТМО",comment:""},
AddressIFNS_FL:{id:607,title:"Код ИФНС для физ. лиц",comment:""},AddressIFNS_UL:{id:608,title:"Код ИФНС для юр. лиц",comment:""},AddressActualABR:{id:609,title:"Актуальный АБ? -код",comment:""},AddressDetectedABR:{id:610,title:"? аспознанный АБ? -код",comment:""},AddressQuality_Base:{id:700,title:"Отсюда начинаются поля с показателями качества обработки адреса",comment:""},AddressPrecision:{id:701,title:"Точность распознавания",comment:""},AddressRecall:{id:702,title:"Полнота распознавания",comment:""},
AddressCanonicFields:{id:703,title:"Целевое количество полей",comment:""},AddressDetectedFields:{id:704,title:"? аспознанное количество полей",comment:""},AddressVerifiedNumericFields:{id:705,title:"Количество верифицированных числовых полей по адресной БД",comment:""},AddressDetectorFlags_Base:{id:800,title:"Отсюда начинаются поля с флагами распознанного адреса",comment:""},AddressIncompleteFlag:{id:801,title:"Признак Incomplete: 'Адрес не является завершенным'",comment:""},AddressChildIsSkippedFlag:{id:802,
title:"Признак ChildIsSkipped: 'Возможно, адрес заполнен не до конца'",comment:""},AddressHouseIsAbsentFlag:{id:803,title:"Признак HouseIsAbsent: 'Не распознан дом, корпус и строение'",comment:""},AddressRestoredPlaceOrCityFlag:{id:804,title:"Признак RestoredPlaceOrCity: 'Населенный пункт или город восстановлен, но не распознан'",comment:""},AddressFoundInSearchMode:{id:805,title:"Признак FoundInSearchMode: 'Адрес распознан в режиме нечеткого поиска'",comment:""},AddressUndetectedZip:{id:806,title:"Признак UndetectedZip: 'В адресе не указан индекс'",
comment:""},AddressImpreciseZip:{id:807,title:"Признак ImpreciseZip: 'Индекс адреса неточен'",comment:""},AddressProperyFlags_Base:{id:900,title:"Отсюда начинаются поля с флагами-свойствами самого адреса",comment:""},AddressPropertyCityIsRegion:{id:901,title:"Свойство CityIsRegion: 'Адрес принадлежит городу-региону'",comment:""},AddressPropertyCenterOfRegion:{id:902,title:"Свойство CenterOfRegion: 'Адрес принадлежит региональному центру'",comment:""},AddressPropertyCenterOfDistrict:{id:903,title:"Свойство CenterOfDistrict: 'Адрес принадлежит районному центру'",
comment:""},AddressPropertyIsObsolet:{id:904,title:"Свойство AddressIsObsolete: 'Адрес устарел. Вернули его актуальную версию'",comment:""},AddressPropertyIsNonexistent:{id:905,title:"Свойство AddressIsNonexistent: 'Адрес не существует'",comment:""},AddressFilterFlags_Base:{id:1E3,title:"Отсюда начинаются поля с флагами о причинах отбраковки адреса",comment:""},AddressFilteredByMaskFlag:{id:1001,title:"Признак FilteredByMask: 'Адрес распознан, но принудительно отбракован'",comment:""},AddressFilteredByZipFlag:{id:1002,
title:"Признак FilteredByZip: 'Адрес отбракован по почтовому индексу'",comment:""},AddressFilteredUnstableDetectionFlag:{id:1003,title:"Признак FilteredUnstableDetection: 'Адрес неуверенно распознан'",comment:""},AddressFilteredByUserFlag:{id:1004,title:"Признак FilteredByUser: 'Адрес отбракован пользовательским фильтром'",comment:""},AddressAbnormalDetectionFlag:{id:1005,title:"Признак AbnormalDetection: 'Адрес отбракован из-за неоднозначного распознавания'",comment:""},AddressAdminOkrugName:{id:1101,
title:"Имя админ. округа города",comment:""},AddressAdminOkrugType:{id:1102,title:"Тип админ. округа города",common:""},AddressAdminAreaName:{id:1103,title:"Имя городского района",common:""},AddressAdminAreaType:{id:1104,title:"Тип городского района",common:""},AddressRingRoadName:{id:1105,title:"Название кольцевой дороги",comment:""},AddressRingRoadShort:{id:1106,title:"Краткое название кольцевой дороги",common:""},AddressInRingFlag:{id:1107,title:"Признак: 'Адрес находится внутри кольца'",common:""},
AddressRingRoadDist:{id:1108,title:"? асстояние до кольца",common:""},AddressTimeZone:{id:1109,title:"Часовая зона по UTC",common:""},AddressStation1_Type:{id:1151,title:"Тип первой станции",comment:""},AddressStation1_Name:{id:1152,title:"Название первой станции",comment:""},AddressStation1_Line:{id:1153,title:"Линия первой станции",comment:""},AddressStation1_Net:{id:1154,title:"Транспортная сеть первой станции",comment:""},AddressStation1_Dist:{id:1155,title:"? асстояние до первой станции",comment:""},
AddressStation2_Type:{id:1156,title:"Тип второй станции",comment:""},AddressStation2_Name:{id:1157,title:"Название второй станции",comment:""},AddressStation2_Line:{id:1158,title:"Линия второй станции",comment:""},AddressStation2_Net:{id:1159,title:"Транспортная сеть второй станции",comment:""},AddressStation2_Dist:{id:1160,title:"? асстояние до второй станции",comment:""},AddressStation3_Type:{id:1161,title:"Тип третьей станции",comment:""},AddressStation3_Name:{id:1162,title:"Название третьей станции",
comment:""},AddressStation3_Line:{id:1163,title:"Линия третьей станции",comment:""},AddressStation3_Net:{id:1164,title:"Транспортная сеть третьей станции",comment:""},AddressStation3_Dist:{id:1165,title:"? асстояние до третьей станции",comment:""},Phone_Base:{id:2E3,title:"Отсюда начинаются поля телефонного номера",comment:""},PhoneNumber:{id:2001,title:"Номер телефона",comment:""},PhoneRange_Base:{id:2100,title:"Информация о диапазоне, которому принадлежит номер",comment:""},PhoneZone:{id:2101,title:"Код зоны",
comment:""},PhoneRangeFirstNumber:{id:2102,title:"Первый номер диапазона",comment:""},PhoneRangeLastNumber:{id:2103,title:"Последний номер диапазона",comment:""},PhoneRangeOperator:{id:2104,title:"Оператор связи",comment:""},PhoneBinding_Base:{id:2200,title:"Отсюда начинаются поля с информацией о привязках телефона к адресным объектам",comment:""},PhoneBindingAddressCode_1:{id:2201,title:"АБ? -код первого адресного объекта, к которому привязан номер",comment:""},PhoneBindingAddressCode_2:{id:2202,
title:"АБ? -код второго адресного объекта, к которому привязан номер",comment:""},PhoneBindingAddressCode_3:{id:2203,title:"АБ? -код третьего адресного объекта, к которому привязан номер",comment:""},PhoneBindingAddressName_1:{id:2204,title:"Имя первого адресного объекта, к которому привязан номер",comment:""},PhoneBindingAddressName_2:{id:2205,title:"Имя второго адресного объекта, к которому привязан номер",comment:""},PhoneBindingAddressName_3:{id:2206,title:"Имя третьего адресного объекта, к которому привязан номер",
comment:""},PhoneDetectorFlags_Base:{id:2300,title:"Отсюда начинаются поля с информацией о флагах телефонного номера, присвоенных ему детектором",comment:""},PhoneVerifiedByAddressFlag:{id:2301,title:"Признак VerifiedByAddress: Телефон соответствует адресу",comment:""},PhoneRestoredZoneFlag:{id:2302,title:"Признак RestoredZone: Код зоны телефона восстановлен по адресу",comment:""},PhoneFlags_Base:{id:2400,title:"Отсюда начинаются поля с информацией о флагах телефонного номера",comment:""},PhoneIsMobile:{id:2401,
title:"Является ли номер мобильным",comment:""},PhoneTimeZone:{id:2402,title:"Часовая зона по UTC",comment:""},Person_Base:{id:3E3,title:"Отсюда начинаются поля с информацией о ФИО",comment:""},PersonLastName:{id:3001,title:"Фамилия персоны",comment:""},PersonFirstName:{id:3002,title:"Имя персоны",comment:""},PersonPatronym:{id:3003,title:"Отчество персоны",comment:""},PersonGender:{id:3004,title:"Пол персоны",comment:""},PersonDomain:{id:3005,title:"Этнический домен ФИО",comment:""},PersonLastNameDomain:{id:3006,
title:"Этнический домен фамилии",comment:""},PersonFirstNameDomain:{id:3007,title:"Этнический домен имени",comment:""},PersonPatronymDomain:{id:3008,title:"Этнический домен отчества",comment:""},PersonCompatibility:{id:3009,title:"Совместимость компонентов ФИО по этническому домену",comment:""},PersonPrecision:{id:3010,title:"Точность распознавания",comment:""},PersonRecall:{id:3011,title:"Полнота распознавания",comment:""},InvalidItem:{id:-1,title:"Невалидный CSV-элемент",comment:""}},DebitType:{Invalid:{id:0,
title:"Невалидный тип списания"},Registry:{id:1,title:"Списание за обработку реестра"},Requests:{id:2,title:"Списание за использование API"}},PaymentSource:{Yandex:{id:0,title:"Яндекс.Касса"},Admin:{id:1,title:"Администратор сервиса"},Robokassa:{id:2,title:"? обокасса"}},YandexPaymentType:{PC:"Яндекс.Деньги",AC:"Банковская карта",MC:"Мобильный телефон",GP:"Касса или терминал",WM:"WebMoney",SB:"Сбербанк",MP:"Мобильный терминал",AB:"Альфа-Клик",MA:"MasterPass",PB:"Промсвязьбанк",QW:"QIWI Wallet"},AccountType:{Invalid:{id:0,
title:"Некорректная учетная запись",short_name:"Некорректная"},Standart:{id:1,title:"Стандартная учетная запись",short_name:"Стандартная"},Partner:{id:2,title:"Партнерская учетная запись",short_name:"Партнерская"}},AccountStatus:{Active:{id:0,title:"Активированная"},WaitingForActivation:{id:1,title:"Неактивированная"},Blocked:{id:2,title:"Заблокированная"}},Lang:{Russian:{id:0,title:"? усский",iso_name:"ru"},English:{id:1,title:"English",iso_name:"en"}},LayoutGet:function(a,b,d,e){$.ajax({type:"GET",
url:"site/user/layout/get?output=json;type="+a+";id="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},LayoutStd:function(a,b,d){$.ajax({type:"GET",url:"site/user/layout/std?output=json;type="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},LayoutList:function(a,b,d){$.ajax({type:"GET",
url:"site/user/layout/list?output=json|short;type="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},LayoutPut:function(a,b,d,e){$.ajax({type:"POST",url:"site/user/layout/put?output=json;type="+a,contentType:"application/json; charset=utf-8",dataType:"json",data:b?JSON.stringify(b):"",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},
LayoutDel:function(a,b,d,e){$.ajax({type:"GET",url:"site/user/layout/del?output=json;type="+a+";id="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},RegistryGet:function(a,b,d){$.ajax({type:"GET",url:"site/user/registry/get?output=json;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,
b,d)}})},RegistryDel:function(a,b,d){$.ajax({type:"GET",url:"site/user/registry/del?output=json|short;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},RegistryScheme:function(a,b,d,e){$.ajax({type:"POST",url:"site/user/registry/scheme?output=json|short;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",data:b?JSON.stringify(b):"",cache:!1,context:this,error:FailServiceRequest,
success:function(a){HandleServiceResponse(a,d,e)}})},RegistryFilter:function(a,b,d,e){$.ajax({type:"POST",url:"site/user/registry/filter?output=json|short;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",data:b?JSON.stringify(b):"",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},RegistryList:function(a,b,d,e,c,f){$.ajax({type:"GET",url:"site/user/registry/list?output=json|short|reverse;month="+d+";year="+e+";size="+b+";exclude=1;id="+
a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,c,f)}})},RegistryStat:function(a,b,d,e){$.ajax({type:"GET",url:"site/user/registry/stat?output=json;month="+a+";year="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},RegistryStatRange:function(a,b,d,e){a=a?a.toISOString():"";b=b?
(new Date(b.getTime()+864E5-1)).toISOString():"";$.ajax({type:"GET",url:"site/user/registry/stat?output=json;time1="+a+";time2="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},RegistryStatlist:function(a,b,d,e,c,f){b=b?b.toISOString():"";d=d?(new Date(d.getTime()+864E5-1)).toISOString():"";a="site/user/registry/statlist?output=json|short|reverse;time1="+b+";time2="+d+";size="+a;$.ajax({type:"GET",
url:1==e?a+";exclude=1":a+";exclude=0",contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,c,f)}})},APIHistoryStat:function(a,b,d,e){$.ajax({type:"GET",url:"site/user/apihistory/stat?output=json;month="+a+";year="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},APIHistoryStatRange:function(a,
b,d,e){a=a?a.toISOString():"";b=b?(new Date(b.getTime()+864E5-1)).toISOString():"";$.ajax({type:"GET",url:"site/user/apihistory/stat?output=json;time1="+a+";time2="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,e)}})},APIHistoryStatlist:function(a,b,d,e,c,f){b=b?b.toISOString():"";d=d?(new Date(d.getTime()+864E5-1)).toISOString():"";a="site/user/apihistory/statlist?output=json|short|reverse;time1="+
b+";time2="+d+";size="+a;$.ajax({type:"GET",url:1==e?a+";exclude=1":a+";exclude=0",contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,c,f)}})},APIHistoryList:function(a,b,d,c,g,f){d=d?d.toISOString():"";c=c?(new Date(c.getTime()+864E5-1)).toISOString():"";$.ajax({type:"GET",url:"site/user/apihistory/list?output=json|short|reverse;time1="+d+";time2="+c+";size="+b+";exclude=1;first_id="+a,contentType:"application/json; charset=utf-8",
dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,g,f)}})},APIHistoryRange:function(a,b,d,c,g){$.ajax({type:"GET",url:"site/user/apihistory/range?output=json;first_id="+a+";last_id="+b+";type="+d,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,c,g)}})},RegistryProcess:function(a,b,d){$.ajax({type:"GET",url:"site/user/registry/process?output=json;id="+
a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},RegistryProgress:function(a,b,d){$.ajax({type:"GET",url:"site/user/registry/progress?output=json;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},RegistryReport:function(a,b){window.location.href="site/user/registry/report?output=json;id="+
a+";report="+b},SchemeGet:function(a,b,d){$.ajax({type:"GET",url:"site/user/scheme/get?output=json;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},SchemeList:function(a,b){$.ajax({type:"GET",url:"site/user/scheme/list?output=json|short",contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(d){HandleServiceResponse(d,
a,b)}})},SchemePut:function(a,b,d){$.ajax({type:"POST",url:"site/user/scheme/put?output=json",contentType:"application/json; charset=utf-8",dataType:"json",data:a?JSON.stringify(a):"",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},SchemeDel:function(a,b,d){$.ajax({type:"GET",url:"site/user/scheme/del?output=json;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,
b,d)}})},ToolsReportFilter:function(a,b,d,c){$.ajax({type:"POST",url:"site/user/tools/reportfilter?output=json;type="+a,contentType:"application/json; charset=utf-8",dataType:"json",data:b,cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,c)}})},FilterGet:function(a,b,d,c){$.ajax({type:"GET",url:"site/user/filter/get?output=json;type="+a+";id="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,
success:function(a){HandleServiceResponse(a,d,c)}})},FilterList:function(a,b,d){$.ajax({type:"GET",url:"site/user/filter/list?output=json|short;type="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},FilterPut:function(a,b,d,c){$.ajax({type:"POST",url:"site/user/filter/put?output=json;type="+a,contentType:"application/json; charset=utf-8",dataType:"json",data:b?JSON.stringify(b):"",cache:!1,
context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,c)}})},FilterDel:function(a,b,d,c){$.ajax({type:"GET",url:"site/user/filter/del?output=json;type="+a+";id="+b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,c)}})},CleanseAddress:function(a,b,d,c){b=$.extend({},b);b.query=a;$.ajax({type:"GET",url:"site/cleanse/address?input=utf8;output=json|acodes|apretty|ainabr;",
data:b,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,d,c)}})},MoneyPayments:function(a,b,d,c,g,f){d=d?d.toISOString():"";c=c?(new Date(c.getTime()+864E5-1)).toISOString():"";$.ajax({type:"GET",url:"site/user/money/payments?output=json|reverse;time1="+d+";time2="+c+";size="+b+";exclude=1;id="+a,contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,
success:function(a){HandleServiceResponse(a,g,f)}})},AccountGet:function(a,b){$.ajax({type:"GET",url:"site/user/account/get?output=json",contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(d){HandleServiceResponse(d,a,b)}})},MoneyPayPrepare_Yandex:function(a,b,d){$.ajax({type:"POST",url:"site/user/money/payprepare/yandex?input=json;output=json",contentType:"application/json; charset=utf-8",dataType:"json",data:a,cache:!1,context:this,
error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},MoneyPayPrepare_Robokassa:function(a,b,d){$.ajax({type:"POST",url:"site/user/money/payprepare/robokassa?input=json;output=json",contentType:"application/json; charset=utf-8",dataType:"json",data:a,cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},ProfileGet:function(a,b){$.ajax({type:"GET",url:"site/user/profile/get?input=json;output=json",contentType:"application/json; charset=utf-8",
dataType:"json",cache:!1,context:this,error:FailServiceRequest,success:function(d){HandleServiceResponse(d,a,b)}})},ProfilePut:function(a,b,d){$.ajax({type:"POST",url:"site/user/profile/put?input=json;output=json",contentType:"application/json; charset=utf-8",dataType:"json",data:a?JSON.stringify(a):"",cache:!1,context:this,error:FailServiceRequest,success:function(a){HandleServiceResponse(a,b,d)}})},GetDataTypeTitle:function(a){var b="Неизвестный тип";$.each(this.DataType,function(d,c){if(c.id==
a)return b=c.title,!1});return b},GetCSVItemTitle:function(a){var b="Неизвестный CSV-элемент";$.each(this.CSVItem,function(c,e){if(e.id==a)return b=e.title,!1});return b},GetYandexPaymentTypeTitle:function(a){var b="Неизвестный тип платежа";$.each(this.YandexPaymentType,function(c,e){if(c==a)return b=e,!1});return b},GetAccountTypeTitle:function(a){var b="Некорретная учетная запись";$.each(this.AccountType,function(c,e){if(e.id==a)return b=e.title,!1});return b},GetLanguageISOName:function(a){var b=
this.Lang.Russian.iso_name;$.each(this.Lang,function(c,e){if(e.id==a)return b=e.iso_name,!1});return b},GetRegistryDownloadCookieName:function(a,b){return"registry_download_"+a+"_"+b},Init:function(){}};c.Init();return c}
function CreateAhunterConfig(){return{Registry:{BatchSize:5,StatlistSize:10,ProgressPeriod:1E3,ReportWaitingPeriod:1E3},History:{FirstYear:2014,BatchSize:10,StatlistSize:10},Users:{BatchSize:10,PollingPeriod:1E3},Misc:{StatisticsRefreshPeriod:5E3,ServersRefreshPeriod:1E4,MessageShowDuration:1E3}}}
function CreateAhunterUtils(){return{MonthNames:"Январь Февраль Март Апрель Май Июнь Июль Август Сентябрь Октябрь Ноябрь Декабрь".split(" "),FormToObject:function(c){c=$(c).serializeArray();var a={};$.each(c,function(b,c){a[c.name]=c.value});return a},CreateDateFromService:function(c){c=/(\d{4,4})-(\d{2,2})-(\d{2,2})T(\d{2,2}):(\d{2,2}):(\d{2,2}).(\d{3,3})Z/g.exec(c);return new Date(Date.UTC(c[1],c[2]-1,c[3],c[4],c[5],c[6],c[7]))},DateToService:function(c){var a="";c&&(a=function(a){10>a&&(a="0"+
a);return a},a=c.getFullYear()+"-"+a(c.getMonth()+1)+"-"+a(c.getDate())+"T"+a(c.getHours())+":"+a(c.getMinutes())+":"+a(c.getSeconds())+"."+(c.getMilliseconds()/1E3).toFixed(3).slice(2,5)+"Z");return a},DateToString:function(c){return("00"+c.getUTCDate()).slice(-2)+"."+("00"+(c.getUTCMonth()+1)).slice(-2)+"."+c.getUTCFullYear()},NumberToString:function(c,a,b){var d="";b||(b=3);a||(a=" ");for(var e=Math.pow(10,b);0!=c;){var g=Math.floor(c%e);c>e&&(g=(g/e).toFixed(b).slice(2,2+b));d=g+d;c=Math.floor(c/
e);0!=c&&(d=a+d)}return d},FilterList:function(c,a){for(var b=c.length-1;0<=b;b--)a.call(c[b])&&c.splice(b,1)},CopyObject:function(c,a){$.each(a,function(b,c){delete a[b]});$.extend(!0,a,c)},Move:function(c,a,b){var d=c[a];c.splice(a,1);c.splice(b,0,d)},GetCookie:function(c){var a=null;c=document.cookie.split(c+"=");2==c.length&&(a=c.pop(),c=a.indexOf(";"),0<=c&&(a=a.substr(0,c)));return a},DelCookie:function(c){document.cookie=encodeURIComponent(c)+"=deleted; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT"},
ParseNumber:function(c,a){return 0<c.length&&isNaN(parseInt(c))?a:0<c.length?parseInt(c):0},GetHumanReadableBytes:function(c){var a="";return a=1048576>c?(c/1024).toFixed(2)+" Kb":1073741824>c?(c/1048576).toFixed(2)+" Mb":(c/1073741824).toFixed(2)+" Gb"},EscapeHTML:function(c){var a={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"};return String(c).replace(/[&<>"'\/]/g,function(b){return a[b]})}}}
function CreateBasicMessageDialog(c,a,b){return{Title:c,Message:a,Details:b,jDialog:null,jMessage:$('<div class="u-Article u-ArticleMid"></div>'),jShowDetailsButton:$('<div class="b-BPaddingStd"><a class="n-Local">Технические детали...</a></div>'),jDetails:$('<div class="u-BoxSharp1 b-VPaddingMin b-HPaddingMin b-Hidden"></div>'),Show:function(){var a=this;this.jMessage.dialog&&(this.jDialog=$('<div id="js-BasicMessageDialog"></div>'),this.jDialog.attr("title",this.Title),this.jDialog.append(this.jMessage),
this.jMessage.append(this.Message),this.Details&&0<this.Details.length&&(this.jShowDetailsButton.off().click(function(){a.jDetails.slideDown(200)}),this.jMessage.append(this.jShowDetailsButton),this.jMessage.append(this.jDetails),this.jDetails.append(this.Details)),this.jDialog.dialog({autoOpen:!1,modal:!0,width:440,position:{my:"center",at:"center",of:window,using:function(a,b){$(this).css({top:$(window).height()/2-$(this).height()/2,left:$(window).width()/2-$(this).width()/2,position:"fixed"})}},
buttons:[{text:"Ок",click:function(){a.Hide()}}],close:function(){a.Hide()}}),this.jDialog.dialog("open"))},Hide:function(){this.jDialog&&(this.jDialog.dialog("destroy"),this.jDialog.remove(),this.jDialog=null)}}}function CreateStaticSuccessMessage(c){return CreateBasicMessageDialog("Мы сделали это!",c)}function CreateStaticInfoMessage(c){return CreateBasicMessageDialog("Это нужно иметь в виду",c)}function CreateStaticErrorMessage(c,a){return CreateBasicMessageDialog("Что-то пошло не так",c,a)}
function CreateServiceErrorMessage(c){c={dialog:null,errors:null!=c?c.errors:null,IsError:function(){return this.errors&&0<this.errors.length},Show:function(){var a=0;this.errors&&$.each(this.errors,function(b,c){a+=$("#"+c.name).slideDown(200).length});a||this.dialog.Show()},Hide:function(){$(".u-Error").hide();this.dialog.Hide()},Init:function(){var a="",b="";null!=this.errors&&$.each(this.errors,function(c,e){e.description.length&&(a+=e.description+"\n");b=e.text.length?b+("<pre>"+e.text+"</pre>"):
b+(e.name+"\n")});this.dialog=0<a.length?CreateStaticErrorMessage(a,b):CreateStaticErrorMessage(b)}};c.Init();return c}function FailServiceRequest(c,a,b){CreateStaticErrorMessage('Не удалось отправить запрос на сервис. Сервис вернул следующий результат: "'+a+": "+b+'"').Show()}function HandleServiceResponse(c,a,b){var d=CreateServiceErrorMessage(c);d.IsError()?d.Show():a&&b&&b.call(a,c)}
function CreateAbstractEditorDialog(c,a){return{jDialog:c.clone(!0).removeAttr("id"),SaveAndClose:function(){this.Save();this.Close()},Close:function(){this.jDialog&&(this.jDialog.dialog("destroy"),this.jDialog.remove(),this.jDialog=null)},Open:function(b,c){var e=this;this.Fill&&this.Fill();this.jDialog.find("input[type='text']").off().keypress(function(a){if(a.keyCode==$.ui.keyCode.ENTER)return e.SaveAndClose(),!1});this.jDialog.dialog({width:a,title:c,modal:!0,position:b?{my:"center bottom",at:"center top",
of:b}:{my:"center center",at:"center center",of:window},buttons:[{text:"Ок",click:function(){e.SaveAndClose()}},{text:"Отмена",click:function(){e.Close()}}],close:function(){e.Close()}})}}}
function CreatePopupMenu(c,a,b){return{jOwner:c,Objects:a,ItemsPerColumn:b,Receiver:null,ReceiverFunc:null,Selected:null,jMenu:null,AddMenu:function(a,b){var c=this,f=$('<div class="u-PopupMenu js-PopupMenu" style="display: none;position: absolute"></div>');a.append(f);null==this.jMenu&&(this.jMenu=f);var h=$('<div class="u-PopupMenuColumn"></div>');f.append(h);$.each(b,function(a,b){var d;null==b?d=$('<div class="u-MenuDelimiter js-PopupMenuItem u-PopupMenuItem"></div>'):(b.GetTitle?d=$('<div class="js-PopupMenuItem u-PopupMenuItem">'+
b.GetTitle()+"</div>"):b.title?d=$('<div class="js-PopupMenuItem u-PopupMenuItem">'+b.title+"</div>"):b.name&&(d=$('<div class="js-PopupMenuItem u-PopupMenuItem">'+b.name+"</div>")),b.disabled&&d.addClass("ui-state-disabled"),void 0===b.submenu?b.disabled?d.click(function(){return!1}):d.click(function(){c.ReceiverFunc.call(c.Receiver,b);c.Selected=b}):(d.addClass("u-PopupMenuItemHasChildren"),d.click(function(){if(!c.Selected)return!1}),c.AddMenu(d,b.submenu)));h.append(d);h.children().length==c.ItemsPerColumn&&
0<c.ItemsPerColumn&&(h=$('<div class="u-PopupMenuColumn"></div>'),f.append(h))})},Show:function(a,b,c,f){var h=this;$(".js-PopupMenu").hide();this.Receiver=c;this.ReceiverFunc=f;this.AddMenu(this.jOwner,this.Objects);this.jMenu.menu({items:".js-PopupMenuItem",menus:".js-PopupMenu"});b?this.jMenu.show().position({my:"left top",at:"left bottom",of:a}):this.jMenu.show().position({my:"left bottom",at:"left top",of:a});$(document).one("click",function(){h.Close()})},Close:function(){this.jMenu.hide();
this.jMenu.menu("destroy");this.jMenu.remove()}}}
function CreateConfirmationDialog(c){return{Message:c,jDialog:null,jMessage:$('<div class="u-Article u-ArticleMid" autofocus="1"></div>'),Open:function(a,b){var c=this;this.jDialog=$('<div id="js-BasicConfirmationDialog"></div>');this.jDialog.attr("title","Необходимо подтвредить данное действие");this.jDialog.append(this.jMessage);this.jMessage.append(this.Message);this.jDialog.dialog({autoOpen:!1,modal:!0,width:440,position:{my:"center",at:"center",of:window,using:function(a,b){$(this).css({top:$(window).height()/
2-$(this).height()/2,left:$(window).width()/2-$(this).width()/2,position:"fixed"})}},buttons:[{text:"Да",click:function(){b.call(a,!0);c.Close()}},{text:"Нет",click:function(){b.call(a,!1);c.Close()}}],close:function(){c.Close()}});this.jDialog.dialog("open")},Close:function(){this.jDialog&&(this.jDialog.dialog("destroy"),this.jDialog.remove(),this.jDialog=null)}}};